ALTER TABLE public.vision_tests
  ADD COLUMN IF NOT EXISTS frame_analysis_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS frame_analysis_status text,
  ADD COLUMN IF NOT EXISTS marked_by text DEFAULT 'user',
  ADD COLUMN IF NOT EXISTS verified_by_coach boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS takeoff_frame integer,
  ADD COLUMN IF NOT EXISTS landing_frame integer,
  ADD COLUMN IF NOT EXISTS start_frame integer,
  ADD COLUMN IF NOT EXISTS finish_frame integer,
  ADD COLUMN IF NOT EXISTS first_contact_frame integer,
  ADD COLUMN IF NOT EXISTS last_contact_frame integer,
  ADD COLUMN IF NOT EXISTS entry_frame integer,
  ADD COLUMN IF NOT EXISTS braking_start_frame integer,
  ADD COLUMN IF NOT EXISTS stop_frame integer,
  ADD COLUMN IF NOT EXISTS exit_frame integer,
  ADD COLUMN IF NOT EXISTS frame_count integer,
  ADD COLUMN IF NOT EXISTS flight_time numeric,
  ADD COLUMN IF NOT EXISTS sprint_time numeric,
  ADD COLUMN IF NOT EXISTS braking_time numeric,
  ADD COLUMN IF NOT EXISTS jump_height_cm numeric,
  ADD COLUMN IF NOT EXISTS distance_m numeric,
  ADD COLUMN IF NOT EXISTS distance_cm numeric,
  ADD COLUMN IF NOT EXISTS speed_m_s numeric,
  ADD COLUMN IF NOT EXISTS speed_km_h numeric,
  ADD COLUMN IF NOT EXISTS number_of_contacts integer;