// Jedyny plik konfiguracyjny ze scenariuszami Football IQ.
// Układ współrzędnych: boisko 100 x 140, kierunek ataku = malejące y (do góry).
// Nowe pozycje/scenariusze dodaje się wyłącznie tutaj.

import type { IQMarker, IQScenario, IQTarget } from "./types";

function m(
  id: string,
  kind: IQMarker["kind"],
  x: number,
  y: number,
  label?: string,
): IQMarker {
  return { id, kind, x, y, label };
}

function t(
  id: string,
  x: number,
  y: number,
  label: string,
  rating: IQTarget["rating"],
  explanation: string,
  consequence: string,
  radius?: number,
): IQTarget {
  return { id, x, y, label, rating, explanation, consequence, radius };
}

export const IQ_SCENARIOS: IQScenario[] = [
  /* ---------------------------------------------------------------- OBROŃCA */
  {
    id: "def-a-1",
    position: "defender",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Wyprowadzenie spod pressingu",
    description:
      "Masz piłkę przy własnym polu karnym, jeden napastnik atakuje Cię z półdystansu. Boczny obrońca jest wolny, pomocnik w środku ma przeciwnika za plecami.",
    interaction: "pass",
    markers: [
      m("self", "self", 42, 108, "Ty"),
      m("ball", "ball", 44, 110),
      m("mate-wide", "mate", 14, 96, "Boczny"),
      m("mate-pivot", "mate", 52, 84, "Pomocnik"),
      m("mate-long", "mate", 62, 40, "Napastnik"),
      m("opp-press", "opponent", 50, 96),
      m("opp-mark", "opponent", 56, 78),
    ],
    targets: [
      t(
        "mate-wide",
        14,
        96,
        "Podanie na bocznego obrońcę",
        "optimal",
        "Boczny jest wolny i ustawiony bokiem do gry — po przyjęciu widzi całe boisko i wychodzicie z pressingu jednym podaniem.",
        "Zespół przenosi grę na wolną stronę i atakuje w otwartej przestrzeni.",
      ),
      t(
        "mate-pivot",
        52,
        84,
        "Podanie w środek",
        "risky",
        "Pomocnik ma przeciwnika za plecami i jest ustawiony tyłem — to podanie może być logiczne, ale wymaga idealnej jakości.",
        "Przy przeciętnym podaniu tracicie piłkę w strefie, z której przeciwnik strzela.",
      ),
      t(
        "mate-long",
        62,
        40,
        "Długie podanie do napastnika",
        "safe",
        "Bezpieczne pod względem ryzyka utraty w niebezpiecznej strefie, ale oddajesz inicjatywę i walkę o drugą piłkę.",
        "Gra przenosi się wysoko, jednak posiadanie jest loteryjne.",
      ),
    ],
    missExplanation:
      "Nie wskazałeś partnera — pod pressingiem decyzja musi być natychmiastowa.",
    missConsequence: "Zwłoka kończy się odbiorem piłki na Twojej połowie.",
  },
  {
    id: "def-a-2",
    position: "defender",
    phase: "attack",
    theme: "Utrzymywanie szerokości",
    title: "Ustawienie przy budowaniu akcji",
    description:
      "Twój stoper ma piłkę, zespół rozpoczyna wyprowadzenie. Wskaż strefę, w której powinieneś się ustawić.",
    interaction: "zone",
    markers: [
      m("self", "self", 40, 104, "Ty"),
      m("mate-cb", "mate", 62, 110, "Stoper"),
      m("ball", "ball", 64, 112),
      m("mate-mid", "mate", 50, 82, "Pomocnik"),
      m("opp-1", "opponent", 54, 96),
      m("opp-2", "opponent", 34, 88),
    ],
    targets: [
      t(
        "wide",
        12,
        92,
        "Szeroko przy linii",
        "optimal",
        "Maksymalna szerokość rozciąga pierwszą linię pressingu i otwiera linię podania wzdłuż boku.",
        "Przeciwnik musi wyjść z bloku, powstaje przestrzeń w środku.",
        18,
      ),
      t(
        "half",
        28,
        86,
        "Półprzestrzeń",
        "safe",
        "Ustawienie logiczne, gdy środek jest wolny, ale nie rozciąga rywala i skraca dystans do krycia.",
        "Podanie jest możliwe, jednak od razu dostajesz presję z dwóch stron.",
        16,
      ),
      t(
        "deep",
        30,
        118,
        "Cofnięcie się do bramkarza",
        "risky",
        "Zwiększa liczbę graczy przy piłce, ale zamyka grę do przodu i zaprasza rywala do pressingu.",
        "Zespół gra w tył i traci tempo akcji.",
        16,
      ),
    ],
    missExplanation:
      "Wybrana strefa nie jest częścią struktury wyprowadzenia dla bocznego obrońcy.",
    missConsequence: "Zespół gra bez szerokości i wpada w pressing.",
  },
  {
    id: "def-a-3",
    position: "defender",
    phase: "attack",
    theme: "Ruch za linię obrony",
    title: "Wejście z drugiej linii",
    description:
      "Skrzydłowy ma piłkę przy linii, obrona rywala jest ustawiona wąsko. Przeciągnij strzałkę pokazującą Twój ruch.",
    interaction: "move",
    markers: [
      m("self", "self", 20, 78, "Ty"),
      m("mate-wing", "mate", 16, 52, "Skrzydłowy"),
      m("ball", "ball", 18, 54),
      m("opp-1", "opponent", 30, 46),
      m("opp-2", "opponent", 48, 40),
    ],
    targets: [
      t(
        "overlap",
        12,
        34,
        "Wyjście na zewnątrz (overlap)",
        "optimal",
        "Biegniesz w wolną przestrzeń za plecami krytego skrzydłowego i zmuszasz obrońcę do decyzji.",
        "Powstaje przewaga 2 na 1 i czysta sytuacja do dogrania.",
      ),
      t(
        "underlap",
        34,
        36,
        "Wejście środkiem (underlap)",
        "risky",
        "Logiczne, gdy rywal broni bardzo szeroko, ale tutaj wbiegasz w strefę zagęszczoną przez dwóch przeciwników.",
        "Podanie łatwo przeciąć, a Ty jesteś wysoko przy stracie.",
      ),
      t(
        "hold",
        22,
        76,
        "Pozostanie w asekuracji",
        "safe",
        "Bezpieczne pod stratę, ale nie tworzy żadnego problemu dla obrony rywala.",
        "Akcja zatrzymuje się na skrzydle bez przewagi.",
      ),
    ],
    missExplanation: "Ten ruch nie wynika z sytuacji przy piłce.",
    missConsequence: "Skrzydłowy zostaje sam w 1 na 1 bez opcji podania.",
  },
  {
    id: "def-a-4",
    position: "defender",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Prowadzenie piłki w wolną przestrzeń",
    description:
      "Nikt Cię nie atakuje, przed Tobą jest kilka metrów wolnej przestrzeni. Przeciągnij strzałkę swojego ruchu z piłką.",
    interaction: "move",
    markers: [
      m("self", "self", 50, 106, "Ty"),
      m("ball", "ball", 52, 108),
      m("mate-l", "mate", 20, 84, "Boczny"),
      m("mate-m", "mate", 58, 76, "Pomocnik"),
      m("opp-1", "opponent", 44, 74),
      m("opp-2", "opponent", 66, 72),
    ],
    targets: [
      t(
        "drive",
        50,
        88,
        "Wyjście z piłką do przodu",
        "optimal",
        "Prowadzenie piłki wciąga rywala i zmusza pomocnika do wyjścia — dopiero wtedy otwiera się linia podania.",
        "Tworzysz przewagę liczbową w środkowej strefie.",
      ),
      t(
        "side",
        26,
        100,
        "Ruch w bok bez postępu",
        "safe",
        "Nie tracisz piłki, ale nie zmieniasz układu obrony rywala.",
        "Akcja jest wolna, rywal spokojnie ustawia blok.",
      ),
      t(
        "back",
        52,
        126,
        "Cofnięcie się z piłką",
        "wrong",
        "Cofasz się mimo wolnej przestrzeni z przodu — oddajesz metry bez powodu.",
        "Zespół gra pod własną bramką i zaprasza pressing.",
      ),
    ],
    missExplanation: "Ruch nie wykorzystuje wolnej przestrzeni przed Tobą.",
    missConsequence: "Tracisz moment, w którym rywal był nieustawiony.",
  },
  {
    id: "def-d-1",
    position: "defender",
    phase: "defense",
    theme: "Asekuracja",
    title: "Partner wychodzi do pressingu",
    description:
      "Twój stoper wyskakuje do napastnika z piłką. Wskaż strefę, w której powinieneś się ustawić.",
    interaction: "zone",
    markers: [
      m("self", "self", 34, 100, "Ty"),
      m("mate-cb", "mate", 58, 86, "Stoper"),
      m("opp-ball", "opponent", 60, 78),
      m("ball", "ball", 62, 80),
      m("opp-run", "opponent", 44, 66),
    ],
    targets: [
      t(
        "cover",
        50,
        104,
        "Za plecami partnera",
        "optimal",
        "Ustawiasz się głębiej i po skosie — jeśli partner zostanie minięty, Ty przejmujesz napastnika.",
        "Zespół nie daje się przełamać jednym podaniem prostopadłym.",
      ),
      t(
        "flat",
        44,
        86,
        "Równo z partnerem",
        "risky",
        "Utrzymuje linię i pułapkę ofsajdową, ale przy minięciu partnera nie ma nikogo za plecami.",
        "Jedno podanie za linię tworzy wyjście sam na sam.",
      ),
      t(
        "press",
        58,
        70,
        "Wyjście do drugiego przeciwnika",
        "wrong",
        "Dwóch obrońców wychodzi jednocześnie i zostawia całą strefę centralną otwartą.",
        "Rywal wchodzi w środek bez oporu.",
      ),
    ],
    missExplanation: "To ustawienie nie zabezpiecza wyjścia partnera.",
    missConsequence: "Obrona zostaje przełamana pierwszym podaniem.",
  },
  {
    id: "def-d-2",
    position: "defender",
    phase: "defense",
    theme: "Krycie",
    title: "Dośrodkowanie z boku",
    description:
      "Rywal przygotowuje dośrodkowanie, w polu karnym są dwaj napastnicy. Wskaż zawodnika, którego kryjesz.",
    interaction: "press",
    markers: [
      m("self", "self", 46, 40, "Ty"),
      m("ball", "ball", 12, 36),
      m("opp-crosser", "opponent", 14, 34),
      m("opp-near", "opponent", 38, 26, "Bliższy słupek"),
      m("opp-far", "opponent", 66, 30, "Dalszy słupek"),
      m("mate-cb", "mate", 34, 32, "Stoper"),
    ],
    targets: [
      t(
        "opp-far",
        66,
        30,
        "Napastnik na dalszym słupku",
        "optimal",
        "Twój partner kontroluje bliższy słupek, więc Twoim obowiązkiem jest niekryty zawodnik na dalszym.",
        "Dośrodkowanie na dalszy słupek zostaje wybite.",
      ),
      t(
        "opp-near",
        38,
        26,
        "Napastnik na bliższym słupku",
        "wrong",
        "Podwajacie krycie tego samego zawodnika i zostawiacie dalszy słupek zupełnie pusty.",
        "Rywal strzela głową z drugiego słupka bez krycia.",
      ),
      t(
        "opp-crosser",
        14,
        34,
        "Wyjście do dośrodkowującego",
        "risky",
        "Skrócenie dystansu do piłki ma sens, ale z tej odległości nie zdążysz, a pole karne zostaje bez obrońcy.",
        "Dośrodkowanie i tak dochodzi, tyle że w przewagę rywala.",
      ),
    ],
    missExplanation: "Nie wskazałeś przeciwnika do krycia.",
    missConsequence: "Napastnik wchodzi w pole karne niekryty.",
  },
  {
    id: "def-d-3",
    position: "defender",
    phase: "defense",
    theme: "Pressing",
    title: "Przyjęcie tyłem do bramki",
    description:
      "Napastnik przyjmuje piłkę tyłem do Twojej bramki, tuż przed Tobą. Wskaż przeciwnika, na którego reagujesz.",
    interaction: "press",
    markers: [
      m("self", "self", 50, 88, "Ty"),
      m("opp-target", "opponent", 50, 76, "Napastnik"),
      m("ball", "ball", 50, 74),
      m("opp-support", "opponent", 72, 68),
      m("mate-mid", "mate", 40, 96, "Pomocnik"),
    ],
    targets: [
      t(
        "opp-target",
        50,
        76,
        "Agresywne wyjście na napastnika",
        "optimal",
        "Zawodnik jest ustawiony tyłem i nie widzi gry — to najlepszy moment na kontakt i odbiór.",
        "Odbierasz piłkę wysoko albo zmuszasz do podania w tył.",
      ),
      t(
        "opp-support",
        72,
        68,
        "Wyjście do wolnego rywala",
        "wrong",
        "Zostawiasz zawodnika przy piłce i pozwalasz mu się obrócić twarzą do bramki.",
        "Napastnik atakuje Twoją obronę w biegu.",
      ),
    ],
    missExplanation: "Nie wskazałeś przeciwnika — pressing wymaga decyzji od razu.",
    missConsequence: "Napastnik obraca się z piłką i gra do przodu.",
  },
  {
    id: "def-d-4",
    position: "defender",
    phase: "defense",
    theme: "Reakcja na kontratak",
    title: "Strata piłki w ataku pozycyjnym",
    description:
      "Zespół stracił piłkę, rywal rusza z kontratakiem, a Ty jesteś ostatnim obrońcą przy piłce. Przeciągnij strzałkę swojego ruchu.",
    interaction: "move",
    markers: [
      m("self", "self", 46, 70, "Ty"),
      m("opp-ball", "opponent", 40, 62, "Rywal z piłką"),
      m("ball", "ball", 40, 60),
      m("opp-run", "opponent", 70, 58),
      m("mate-back", "mate", 56, 104, "Partner"),
    ],
    targets: [
      t(
        "delay",
        44,
        84,
        "Cofanie i spowalnianie akcji",
        "optimal",
        "Jako ostatni obrońca opóźniasz akcję, prowadzisz rywala na bok i czekasz na powrót partnerów.",
        "Kontratak traci tempo, obrona zdąża się ustawić.",
      ),
      t(
        "tackle",
        38,
        60,
        "Wejście w odbiór",
        "risky",
        "Odbiór kończy akcję, ale przy minięciu zostaje otwarta droga do bramki.",
        "Nieudany wślizg oznacza sytuację sam na sam.",
      ),
      t(
        "cover-run",
        70,
        62,
        "Bieg do drugiego rywala",
        "wrong",
        "Zostawiasz zawodnika z piłką bez presji, choć to on jest najgroźniejszy.",
        "Rywal wchodzi w pole karne bez oporu.",
      ),
    ],
    missExplanation: "Ten ruch nie kontroluje zawodnika z piłką.",
    missConsequence: "Kontratak rozwija się w pełnym tempie.",
  },

  /* -------------------------------------------------------------- POMOCNIK */
  {
    id: "mid-a-1",
    position: "midfielder",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Otwarcie linii podania dla stopera",
    description:
      "Stoper ma piłkę, ale przeciwnik stoi w Twoim cieniu podania. Wskaż strefę, w której się ustawiasz.",
    interaction: "zone",
    markers: [
      m("self", "self", 50, 92, "Ty"),
      m("mate-cb", "mate", 50, 116, "Stoper"),
      m("ball", "ball", 52, 118),
      m("opp-shadow", "opponent", 50, 104),
      m("mate-wide", "mate", 16, 92, "Boczny"),
    ],
    targets: [
      t(
        "side-step",
        30,
        94,
        "Krok w bok, poza cień podania",
        "optimal",
        "Wychodzisz z linii krycia i dajesz stoperowi czystą, prostą linię podania.",
        "Piłka wchodzi w środek pola, zespół gra do przodu.",
      ),
      t(
        "drop",
        50,
        108,
        "Zejście do piłki",
        "safe",
        "Ułatwia podanie, ale przyciągasz przeciwnika i cofasz punkt gry.",
        "Zespół utrzymuje piłkę, jednak bez postępu.",
      ),
      t(
        "high",
        54,
        60,
        "Wyjście wysoko między linie",
        "risky",
        "Może być bardzo groźne, ale z tej odległości podanie musi przejść przez dwie linie rywala.",
        "Przechwyt oznacza kontratak w Twoją strefę.",
      ),
    ],
    missExplanation:
      "W tej strefie nadal jesteś w cieniu podania przeciwnika.",
    missConsequence: "Stoper nie ma opcji i gra piłkę w tył.",
  },
  {
    id: "mid-a-2",
    position: "midfielder",
    phase: "attack",
    theme: "Utrzymywanie szerokości",
    title: "Przeniesienie gry",
    description:
      "Masz piłkę w środku, cała gra zebrała się po jednej stronie. Wskaż partnera do podania.",
    interaction: "pass",
    markers: [
      m("self", "self", 60, 78, "Ty"),
      m("ball", "ball", 62, 80),
      m("mate-far", "mate", 12, 66, "Skrzydłowy"),
      m("mate-near", "mate", 76, 70, "Boczny"),
      m("mate-fwd", "mate", 58, 46, "Napastnik"),
      m("opp-1", "opponent", 70, 84),
      m("opp-2", "opponent", 66, 60),
      m("opp-3", "opponent", 50, 52),
    ],
    targets: [
      t(
        "mate-far",
        12,
        66,
        "Przeniesienie na wolną stronę",
        "optimal",
        "Cała obrona rywala jest przesunięta — zmiana strony daje skrzydłowemu przestrzeń i czas.",
        "Skrzydłowy atakuje 1 na 1 w otwartej przestrzeni.",
      ),
      t(
        "mate-near",
        76,
        70,
        "Podanie na bliższą stronę",
        "safe",
        "Utrzymujesz piłkę, ale gracie w strefę, gdzie rywal ma przewagę liczbową.",
        "Akcja zatrzymuje się w zagęszczeniu.",
      ),
      t(
        "mate-fwd",
        58,
        46,
        "Podanie prostopadłe do napastnika",
        "risky",
        "Bardzo groźne, jeśli przejdzie, ale przecina je dwóch ustawionych rywali.",
        "Strata w środku otwiera szybki kontratak.",
      ),
    ],
    missExplanation: "Nie wskazałeś partnera.",
    missConsequence: "Tracisz moment przewagi i wpadasz w pressing.",
  },
  {
    id: "mid-a-3",
    position: "midfielder",
    phase: "attack",
    theme: "Ruch za linię obrony",
    title: "Wbiegnięcie z drugiej linii",
    description:
      "Skrzydłowy prowadzi piłkę do środka, a napastnik ściąga stopera. Przeciągnij strzałkę swojego ruchu.",
    interaction: "move",
    markers: [
      m("self", "self", 52, 74, "Ty"),
      m("mate-wing", "mate", 24, 58, "Skrzydłowy"),
      m("ball", "ball", 26, 60),
      m("mate-fwd", "mate", 58, 34, "Napastnik"),
      m("opp-cb", "opponent", 54, 40),
      m("opp-mid", "opponent", 44, 62),
    ],
    targets: [
      t(
        "run-behind",
        70,
        36,
        "Wbiegnięcie za linię obrony",
        "optimal",
        "Napastnik ściągnął stopera, więc przestrzeń za obroną należy do Ciebie — atakujesz ją w biegu.",
        "Dostajesz podanie za linię i wchodzisz w pole karne.",
      ),
      t(
        "support",
        44,
        76,
        "Ustawienie do podania wstecznego",
        "safe",
        "Daje skrzydłowemu asekurację i utrzymanie piłki, ale nie zagraża bramce.",
        "Akcja jest kontynuowana bez ryzyka i bez okazji.",
      ),
      t(
        "box-edge",
        56,
        50,
        "Wejście przed pole karne",
        "risky",
        "Sensowne pod dogranie, ale wchodzisz w strefę zajętą przez pomocnika rywala.",
        "Podanie zostaje przecięte przed polem karnym.",
      ),
    ],
    missExplanation: "Ten ruch nie atakuje przestrzeni otwartej przez napastnika.",
    missConsequence: "Obrona rywala pozostaje kompletna.",
  },
  {
    id: "mid-a-4",
    position: "midfielder",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Pierwszy kontakt pod presją",
    description:
      "Dostajesz piłkę w środku pola, rywal dochodzi z lewej strony. Wskaż partnera do podania.",
    interaction: "pass",
    markers: [
      m("self", "self", 50, 82, "Ty"),
      m("ball", "ball", 52, 84),
      m("opp-press", "opponent", 38, 80),
      m("mate-right", "mate", 76, 74, "Wolny partner"),
      m("mate-back", "mate", 48, 104, "Stoper"),
      m("mate-fwd", "mate", 54, 44, "Napastnik"),
      m("opp-cb", "opponent", 58, 52),
    ],
    targets: [
      t(
        "mate-right",
        76,
        74,
        "Podanie w kierunku przeciwnym do presji",
        "optimal",
        "Presja nadchodzi z lewej, więc gra w prawo wypuszcza wolnego partnera twarzą do gry.",
        "Zespół gra do przodu jednym kontaktem.",
      ),
      t(
        "mate-back",
        48,
        104,
        "Podanie do stopera",
        "safe",
        "Pewne utrzymanie piłki, ale cofasz akcję i pozwalasz rywalowi ustawić pressing.",
        "Zaczynacie budowanie od nowa.",
      ),
      t(
        "mate-fwd",
        54,
        44,
        "Podanie prostopadłe",
        "risky",
        "Ambitne i logiczne przy dobrym pierwszym kontakcie, ale stoper czyta tę linię.",
        "Przechwyt w środku pola przy Twoim wysokim ustawieniu.",
      ),
    ],
    missExplanation: "Nie wskazałeś partnera pod presją.",
    missConsequence: "Rywal odbiera piłkę w środkowej strefie.",
  },
  {
    id: "mid-d-1",
    position: "midfielder",
    phase: "defense",
    theme: "Ochrona środka",
    title: "Rywal gra bokiem",
    description:
      "Przeciwnik przenosi piłkę na skrzydło, Twoi obrońcy są ustawieni. Wskaż strefę, którą zajmujesz.",
    interaction: "zone",
    markers: [
      m("self", "self", 50, 78, "Ty"),
      m("opp-ball", "opponent", 18, 70),
      m("ball", "ball", 18, 68),
      m("opp-mid", "opponent", 46, 58),
      m("mate-cb", "mate", 46, 100, "Stoper"),
      m("mate-wide", "mate", 20, 86, "Boczny"),
    ],
    targets: [
      t(
        "center",
        42,
        76,
        "Środek pola przed obroną",
        "optimal",
        "Zamykasz podanie w środek i chronisz strefę przed obroną — skrzydło zostaje dla bocznego obrońcy.",
        "Rywal musi grać wokół bloku, bez wejścia w środek.",
      ),
      t(
        "ball-side",
        22,
        74,
        "Dobiegnięcie do piłki",
        "risky",
        "Zwiększa presję na piłkę, ale zostawia środek pola otwarty i podwaja krycie bocznego.",
        "Podanie do środka omija cały Twój blok.",
      ),
      t(
        "deep",
        50,
        104,
        "Cofnięcie się do linii obrony",
        "wrong",
        "Tworzysz nadmiar w obronie i oddajesz strefę, w której rywal przygotowuje strzał.",
        "Rywal gra i strzela z przedpola bez presji.",
      ),
    ],
    missExplanation: "Ta strefa nie chroni środka pola.",
    missConsequence: "Rywal wraca piłką w środek i przyspiesza akcję.",
  },
  {
    id: "mid-d-2",
    position: "midfielder",
    phase: "defense",
    theme: "Pressing",
    title: "Złe przyjęcie rywala",
    description:
      "Pomocnik rywala przyjmuje piłkę zbyt daleko od siebie w środkowej strefie. Wskaż przeciwnika, na którego reagujesz.",
    interaction: "press",
    markers: [
      m("self", "self", 52, 84, "Ty"),
      m("opp-bad", "opponent", 48, 70, "Złe przyjęcie"),
      m("ball", "ball", 44, 66),
      m("opp-free", "opponent", 76, 74),
      m("opp-back", "opponent", 50, 96),
      m("mate-mid", "mate", 66, 88, "Partner"),
    ],
    targets: [
      t(
        "opp-bad",
        48,
        70,
        "Natychmiastowy pressing na zawodnika z piłką",
        "optimal",
        "Złe przyjęcie to sygnał do pressingu — rywal nie kontroluje piłki i nie widzi partnerów.",
        "Odbiór w środku pola i szybki atak na nieustawioną obronę.",
      ),
      t(
        "opp-free",
        76,
        74,
        "Krycie wolnego rywala",
        "safe",
        "Zamyka jedną opcję podania, ale marnujesz najlepszy moment do odbioru.",
        "Rywal opanowuje piłkę i spokojnie gra dalej.",
      ),
      t(
        "opp-back",
        50,
        96,
        "Cofnięcie się na rywala z tyłu",
        "wrong",
        "Reagujesz na zawodnika, który nie ma piłki i nie zagraża Twojej bramce.",
        "Rywal bez presji rozgrywa akcję do przodu.",
      ),
    ],
    missExplanation: "Nie wskazałeś przeciwnika.",
    missConsequence: "Moment na odbiór mija bezpowrotnie.",
  },
  {
    id: "mid-d-3",
    position: "midfielder",
    phase: "defense",
    theme: "Asekuracja",
    title: "Partner wyskakuje do pressingu",
    description:
      "Twój partner z drugiej linii wychodzi do piłki wysoko. Przeciągnij strzałkę swojego ruchu.",
    interaction: "move",
    markers: [
      m("self", "self", 56, 84, "Ty"),
      m("mate-press", "mate", 44, 62, "Partner"),
      m("opp-ball", "opponent", 42, 56),
      m("ball", "ball", 42, 54),
      m("opp-drop", "opponent", 52, 74),
    ],
    targets: [
      t(
        "cover-space",
        48,
        80,
        "Zajęcie strefy za partnerem",
        "optimal",
        "Kiedy partner wyskakuje, Twoim zadaniem jest zamknąć przestrzeń, którą zostawił.",
        "Podanie w wolny środek nie ma adresata.",
      ),
      t(
        "join-press",
        44,
        62,
        "Wspólny pressing",
        "risky",
        "Podwojenie może wymusić stratę, lecz przy ominięciu zostają dwie linie otwarte.",
        "Jedno podanie eliminuje dwóch pomocników.",
      ),
      t(
        "hold-wide",
        76,
        84,
        "Utrzymanie szerokiej pozycji",
        "wrong",
        "Zostawiasz środek pola pusty w momencie, gdy jest najbardziej narażony.",
        "Rywal wchodzi środkiem prosto na Twoją obronę.",
      ),
    ],
    missExplanation: "Ten ruch nie zabezpiecza strefy po wyjściu partnera.",
    missConsequence: "Środek pola zostaje otwarty.",
  },
  {
    id: "mid-d-4",
    position: "midfielder",
    phase: "defense",
    theme: "Reakcja na kontratak",
    title: "Strata piłki wysoko",
    description:
      "Zespół traci piłkę na połowie rywala, obrona jest wysunięta. Wskaż strefę, którą zajmujesz.",
    interaction: "zone",
    markers: [
      m("self", "self", 46, 56, "Ty"),
      m("opp-ball", "opponent", 42, 50),
      m("ball", "ball", 42, 48),
      m("opp-run-l", "opponent", 20, 62),
      m("opp-run-r", "opponent", 72, 60),
      m("mate-cb", "mate", 50, 92, "Stoper"),
    ],
    targets: [
      t(
        "block-center",
        46,
        70,
        "Zamknięcie środkowego kanału",
        "optimal",
        "Kontratak najszybciej rozwija się środkiem — Twoim zadaniem jest ustawić się na drodze piłki i spowolnić akcję.",
        "Rywal musi grać bokiem, zespół zdąża wrócić.",
      ),
      t(
        "chase",
        42,
        50,
        "Pogoń za piłką",
        "risky",
        "Kontrpressing bywa skuteczny natychmiast po stracie, ale tutaj rywal już ruszył i mijasz linię piłki.",
        "Zostajesz z tyłu akcji, a zespół broni w niedoborze.",
      ),
      t(
        "wide",
        74,
        64,
        "Krycie rywala na skrzydle",
        "wrong",
        "Skrzydło może przejąć obrońca — Ty zostawiasz najkrótszą drogę do bramki.",
        "Kontratak przechodzi środkiem bez oporu.",
      ),
    ],
    missExplanation: "Ta strefa nie spowalnia kontrataku.",
    missConsequence: "Rywal atakuje wprost na Waszą obronę.",
  },

  /* ------------------------------------------------------------- NAPASTNIK */
  {
    id: "fwd-a-1",
    position: "forward",
    phase: "attack",
    theme: "Ruch za linię obrony",
    title: "Pomocnik podnosi głowę",
    description:
      "Pomocnik ma piłkę i czas, linia obrony rywala stoi wysoko i płasko. Przeciągnij strzałkę swojego ruchu.",
    interaction: "move",
    markers: [
      m("self", "self", 50, 48, "Ty"),
      m("mate-mid", "mate", 48, 82, "Pomocnik"),
      m("ball", "ball", 50, 84),
      m("opp-cb1", "opponent", 38, 42),
      m("opp-cb2", "opponent", 64, 42),
    ],
    targets: [
      t(
        "diagonal-run",
        70,
        26,
        "Skośny ruch za linię obrony",
        "optimal",
        "Skośny bieg w przerwę między stoperami utrudnia krycie i utrzymuje Cię dłużej na spalonym boku.",
        "Dostajesz podanie za linię i wychodzisz na bramkę.",
      ),
      t(
        "check-to-ball",
        48,
        66,
        "Zejście do piłki",
        "safe",
        "Ułatwia podanie i utrzymanie piłki, ale nie atakuje przestrzeni za obroną.",
        "Zespół utrzymuje posiadanie bez zagrożenia.",
      ),
      t(
        "straight-run",
        50,
        28,
        "Bieg prosto na stopera",
        "risky",
        "Atakujesz przestrzeń, ale biegniesz w krycie i łatwo Cię wypchnąć na spalonego.",
        "Sędzia odgwizduje pozycję spaloną.",
      ),
    ],
    missExplanation: "Ten ruch nie wykorzystuje wysokiej linii obrony.",
    missConsequence: "Pomocnik nie ma komu podać do przodu.",
  },
  {
    id: "fwd-a-2",
    position: "forward",
    phase: "attack",
    theme: "Utrzymywanie szerokości",
    title: "Atak pozycyjny na jednej stronie",
    description:
      "Zespół przygotowuje dośrodkowanie z prawej strony, a w polu karnym jest już jeden partner. Wskaż strefę, którą zajmujesz.",
    interaction: "zone",
    markers: [
      m("self", "self", 48, 40, "Ty"),
      m("mate-wing", "mate", 84, 44, "Skrzydłowy"),
      m("ball", "ball", 86, 46),
      m("mate-near", "mate", 42, 26, "Partner"),
      m("opp-cb1", "opponent", 50, 24),
      m("opp-cb2", "opponent", 62, 30),
    ],
    targets: [
      t(
        "far-post",
        26,
        24,
        "Dalszy słupek",
        "optimal",
        "Partner obsadził bliższy słupek, więc szerokie wejście na dalszy daje Ci pozycję poza plecami obrońców.",
        "Dośrodkowanie na dalszy słupek zastaje Cię niekrytego.",
      ),
      t(
        "penalty-spot",
        50,
        30,
        "Punkt karny",
        "safe",
        "Klasyczna strefa wykończenia, ale stoisz między dwoma obrońcami.",
        "Piłka spada w tłok, szansa jest przypadkowa.",
      ),
      t(
        "edge",
        52,
        52,
        "Wycofanie przed pole karne",
        "risky",
        "Dobre pod dogranie do tyłu, jednak zostawiacie pole karne w niedoborze.",
        "Dośrodkowanie nie ma adresata w polu karnym.",
      ),
    ],
    missExplanation: "Ta strefa nie tworzy zagrożenia przy dośrodkowaniu.",
    missConsequence: "Piłka przechodzi przez pole karne bez uderzenia.",
  },
  {
    id: "fwd-a-3",
    position: "forward",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Stoper wyprowadza piłkę",
    description:
      "Stoper prowadzi piłkę do przodu, środek pola jest zamknięty. Wskaż strefę, w której się ustawiasz.",
    interaction: "zone",
    markers: [
      m("self", "self", 52, 46, "Ty"),
      m("mate-cb", "mate", 50, 100, "Stoper"),
      m("ball", "ball", 52, 102),
      m("opp-mid1", "opponent", 40, 72),
      m("opp-mid2", "opponent", 62, 70),
      m("opp-cb", "opponent", 54, 34),
    ],
    targets: [
      t(
        "between-lines",
        30,
        60,
        "Zejście między linie na wolną stronę",
        "optimal",
        "Wchodzisz w przestrzeń, której nie kontroluje ani pomocnik, ani stoper rywala — stoper ma czystą linię podania.",
        "Przyjmujesz piłkę twarzą do gry w groźnej strefie.",
      ),
      t(
        "stay-high",
        54,
        30,
        "Pozostanie przy stoperach",
        "safe",
        "Utrzymujesz głębokość zespołu, ale odcinasz sobie kontakt z piłką.",
        "Stoper nie ma opcji i gra w bok.",
      ),
      t(
        "deep-drop",
        50,
        84,
        "Głębokie zejście do środka",
        "risky",
        "Dajesz opcję podania, ale wchodzisz między dwóch pomocników rywala i zostawiasz przestrzeń z przodu.",
        "Strata w środku i kontratak przy Waszym wysokim ustawieniu.",
      ),
    ],
    missExplanation: "W tej strefie nie tworzysz linii podania.",
    missConsequence: "Wyprowadzenie kończy się podaniem w bok.",
  },
  {
    id: "fwd-a-4",
    position: "forward",
    phase: "attack",
    theme: "Tworzenie linii podania",
    title: "Przewaga w polu karnym",
    description:
      "Wchodzisz z piłką w pole karne, bramkarz skraca kąt, dwóch partnerów jest w polu karnym. Wskaż partnera do podania.",
    interaction: "pass",
    markers: [
      m("self", "self", 62, 30, "Ty"),
      m("ball", "ball", 62, 28),
      m("mate-center", "mate", 44, 20, "Partner w środku"),
      m("mate-edge", "mate", 56, 44, "Partner z tyłu"),
      m("opp-cb", "opponent", 52, 26),
      m("opp-gk", "opponent", 50, 12, "Bramkarz"),
    ],
    targets: [
      t(
        "mate-center",
        44,
        20,
        "Podanie do partnera w środku",
        "optimal",
        "Bramkarz wyszedł do Ciebie, więc podanie w poprzek zostawia partnerowi pustą bramkę.",
        "Pewna sytuacja bramkowa z bliskiej odległości.",
      ),
      t(
        "mate-edge",
        56,
        44,
        "Podanie do tyłu",
        "safe",
        "Rozsądne, gdy nie ma linii w przód, ale tutaj rezygnujesz z gotowej okazji.",
        "Strzał z dystansu zamiast czystej sytuacji.",
      ),
    ],
    missExplanation: "Nie wskazałeś partnera w polu karnym.",
    missConsequence: "Bramkarz zamyka sytuację przy Twojej zwłoce.",
  },
  {
    id: "fwd-d-1",
    position: "forward",
    phase: "defense",
    theme: "Pressing",
    title: "Rozegranie od bramkarza",
    description:
      "Bramkarz rywala podaje do stopera po Twojej lewej stronie. Wskaż przeciwnika, na którego ruszasz.",
    interaction: "press",
    markers: [
      m("self", "self", 50, 78, "Ty"),
      m("opp-cb-l", "opponent", 34, 96, "Stoper lewy"),
      m("ball", "ball", 34, 98),
      m("opp-cb-r", "opponent", 66, 96, "Stoper prawy"),
      m("opp-gk", "opponent", 50, 118, "Bramkarz"),
      m("mate-mid", "mate", 52, 62, "Partner"),
    ],
    targets: [
      t(
        "opp-cb-l",
        34,
        96,
        "Pressing na stopera z piłką od zewnątrz",
        "optimal",
        "Atakujesz po łuku, zamykając podanie w środek i spychając rywala do linii bocznej.",
        "Rywal gra długo w bok, zespół odzyskuje piłkę wysoko.",
      ),
      t(
        "opp-gk",
        50,
        118,
        "Bieg do bramkarza",
        "risky",
        "Może wymusić błąd, ale piłka jest już poza bramkarzem i tracisz kontakt z akcją.",
        "Stoper spokojnie wyprowadza piłkę.",
      ),
      t(
        "opp-cb-r",
        66,
        96,
        "Krycie drugiego stopera",
        "wrong",
        "Zostawiasz zawodnika z piłką bez presji, choć to on decyduje o kierunku gry.",
        "Rywal wyprowadza akcję bez żadnego oporu.",
      ),
    ],
    missExplanation: "Nie wskazałeś przeciwnika do pressingu.",
    missConsequence: "Rywal wyprowadza piłkę spod bramki.",
  },
  {
    id: "fwd-d-2",
    position: "forward",
    phase: "defense",
    theme: "Ochrona środka",
    title: "Zespół cofa się do bloku",
    description:
      "Rywal ma piłkę w środku pola, Wasz zespół ustawia średni blok. Wskaż strefę, którą zajmujesz.",
    interaction: "zone",
    markers: [
      m("self", "self", 50, 66, "Ty"),
      m("opp-ball", "opponent", 46, 84, "Rywal z piłką"),
      m("ball", "ball", 46, 86),
      m("opp-pivot", "opponent", 52, 74, "Pivot"),
      m("mate-mid", "mate", 48, 56, "Partner"),
    ],
    targets: [
      t(
        "shadow-pivot",
        52,
        72,
        "Cień na środkowego pomocnika",
        "optimal",
        "Ustawiasz się tak, by Twoje ciało zamykało podanie do pivota — bronisz strefy, nie goniąc piłki.",
        "Rywal musi grać bokiem, blok pozostaje zwarty.",
      ),
      t(
        "chase-ball",
        46,
        84,
        "Pogoń za piłką",
        "risky",
        "Pojedynczy pressing bez wsparcia bywa uzasadniony, ale tutaj otwierasz środek za sobą.",
        "Rywal ogrywa Cię jednym podaniem i atakuje blok.",
      ),
      t(
        "drop-deep",
        50,
        100,
        "Powrót do własnej połowy",
        "wrong",
        "Cofasz się zbyt głęboko, zespół traci punkt zaczepienia przy odbiorze.",
        "Po przechwycie nie ma komu podać, piłka natychmiast wraca.",
      ),
    ],
    missExplanation: "Ta strefa nie chroni środka przy średnim bloku.",
    missConsequence: "Rywal wchodzi środkiem między linie.",
  },
  {
    id: "fwd-d-3",
    position: "forward",
    phase: "defense",
    theme: "Krycie",
    title: "Rzut rożny dla rywala",
    description:
      "Bronicie rzutu rożnego, a rywal ustawia gracza na krótkim rogu. Wskaż przeciwnika, którego kryjesz.",
    interaction: "press",
    markers: [
      m("self", "self", 40, 46, "Ty"),
      m("ball", "ball", 8, 14),
      m("opp-corner", "opponent", 8, 16, "Wykonawca"),
      m("opp-short", "opponent", 22, 32, "Krótki róg"),
      m("opp-edge", "opponent", 50, 46, "Przed polem"),
      m("mate-cb", "mate", 44, 26, "Stoper"),
    ],
    targets: [
      t(
        "opp-short",
        22,
        32,
        "Krycie zawodnika na krótkim rogu",
        "optimal",
        "To Twoje standardowe zadanie przy rożnym — zamykasz rozegranie na krótko i nie wchodzisz w tłok.",
        "Rywal musi dośrodkować pod presją albo cofnąć piłkę.",
      ),
      t(
        "opp-edge",
        50,
        46,
        "Krycie zawodnika przed polem karnym",
        "safe",
        "Zamyka strzał po wybiciu, ale krótki róg zostaje wolny.",
        "Rywal rozgrywa krótko i tworzy przewagę na skrzydle.",
      ),
      t(
        "opp-corner",
        8,
        16,
        "Wyjście do wykonawcy",
        "wrong",
        "Blokowanie wykonawcy rożnego jest nieskuteczne i zostawia dwie opcje rozegrania bez krycia.",
        "Rywal gra krótko i wchodzi w pole karne w przewadze.",
      ),
    ],
    missExplanation: "Nie wskazałeś przeciwnika do krycia.",
    missConsequence: "Rywal rozgrywa rożny krótko bez oporu.",
  },
  {
    id: "fwd-d-4",
    position: "forward",
    phase: "defense",
    theme: "Reakcja na kontratak",
    title: "Strata piłki w ataku",
    description:
      "Tracisz piłkę na skraju pola karnego rywala, obrona przechodzi do kontrataku. Przeciągnij strzałkę swojego ruchu.",
    interaction: "move",
    markers: [
      m("self", "self", 52, 40, "Ty"),
      m("opp-ball", "opponent", 58, 44, "Rywal z piłką"),
      m("ball", "ball", 58, 46),
      m("opp-out", "opponent", 84, 56),
      m("mate-mid", "mate", 48, 70, "Partner"),
    ],
    targets: [
      t(
        "counterpress",
        58,
        44,
        "Natychmiastowy kontrpressing",
        "optimal",
        "Pierwsze sekundy po stracie to najlepszy moment na odbiór — rywal nie ma jeszcze kontroli i opcji podania.",
        "Odbieracie piłkę wysoko i wracacie do ataku.",
      ),
      t(
        "cut-pass",
        76,
        52,
        "Zamknięcie podania na skrzydło",
        "safe",
        "Ogranicza wyjście kontratakiem, ale daje rywalowi czas na spokojne rozegranie.",
        "Rywal wyprowadza akcję środkiem.",
      ),
      t(
        "jog-back",
        50,
        76,
        "Spokojny powrót do bloku",
        "risky",
        "Ma sens po nieudanym kontrpressingu, ale teraz oddajesz najłatwiejszy odbiór meczu.",
        "Rywal rusza z kontratakiem w pełnym tempie.",
      ),
    ],
    missExplanation: "Ten ruch nie reaguje na stratę piłki.",
    missConsequence: "Kontratak rozwija się bez żadnej presji.",
  },

  /* ============================================ POZIOM ZAAWANSOWANY ======= */

  /* -------------------------------------------------- OBROŃCA / ATAK ---- */
  {
    id: "def-a-5",
    position: "defender",
    phase: "attack",
    theme: "Zaproszenie pressingu",
    title: "Świadome przyciągnięcie napastnika",
    description:
      "Rywal broni w bloku i nie wychodzi. Twój pomocnik stoi między liniami, ale jest kryty plecami przez „szóstkę” rywala.",
    interaction: "move",
    markers: [
      m("self", "self", 34, 104, "Ty"),
      m("ball", "ball", 36, 106),
      m("mate-cb", "mate", 66, 106, "Stoper"),
      m("mate-10", "mate", 52, 72, "Między liniami"),
      m("opp-st", "opponent", 40, 86, "Napastnik"),
      m("opp-6", "opponent", 54, 64, "Szóstka"),
    ],
    targets: [
      t(
        "carry-in",
        44,
        90,
        "Prowadzenie piłki w kierunku napastnika",
        "optimal",
        "Sam pressing nie przyjdzie. Prowadząc piłkę zmuszasz napastnika do wyjścia, a jego wyjście otwiera linię podania za jego plecami.",
        "Rywal traci kształt na jeden kontakt i wchodzicie w wolne pole między liniami.",
        14,
      ),
      t(
        "carry-wide",
        16,
        96,
        "Prowadzenie w kierunku linii bocznej",
        "safe",
        "Nie tracisz piłki, ale sam zmniejszasz sobie boisko i nikogo nie wyciągasz z pozycji.",
        "Blok rywala przesuwa się bez wysiłku, akcja utyka na skrzydle.",
        13,
      ),
      t(
        "back-cb",
        66,
        106,
        "Cofnięcie na drugiego stopera",
        "risky",
        "Bezpieczne, ale w bloku niskim ciągłe przenoszenie bez prowokacji tylko zużywa czas.",
        "Rywal domyka i zaczynasz akcję od zera.",
        12,
      ),
    ],
    missExplanation:
      "Przy nieruchomym bloku nie pokazałeś żadnego bodźca zmuszającego rywala do decyzji.",
    missConsequence: "Blok pozostaje kompletny, nie powstaje żadna przewaga.",
  },
  {
    id: "def-a-6",
    position: "defender",
    phase: "attack",
    theme: "Gra trzeciego zawodnika",
    title: "Podanie wsteczne jako broń",
    description:
      "Wyprowadzasz piłkę stroną, na której rywal właśnie ustawił pułapkę pressingową. Wolny jest pomocnik cofnięty za linię piłki.",
    interaction: "pass",
    markers: [
      m("self", "self", 22, 96, "Ty"),
      m("ball", "ball", 24, 98),
      m("mate-6", "mate", 48, 112, "Cofnięty pomocnik"),
      m("mate-wing", "mate", 12, 66, "Skrzydłowy"),
      m("mate-cb", "mate", 40, 116, "Stoper"),
      m("opp-wing", "opponent", 20, 78),
      m("opp-8", "opponent", 36, 88),
      m("opp-back", "opponent", 14, 56),
    ],
    targets: [
      t(
        "mate-6",
        48,
        112,
        "Podanie wsteczne do pomocnika",
        "optimal",
        "Pułapka działa tylko wtedy, gdy grasz do przodu. Podanie wstecz przenosi grę o jeden kontakt szybciej niż rywal zdąży przesunąć blok.",
        "Wolna strona otwiera się natychmiast, atakujecie w przewadze.",
      ),
      t(
        "mate-wing",
        12,
        66,
        "Podanie wzdłuż linii do skrzydłowego",
        "wrong",
        "To jest dokładnie podanie, na które czeka rywal — skrzydłowy dostaje piłkę przy linii, kryty i bez pola.",
        "Odbiór przy linii i kontratak w Twoją stronę.",
      ),
      t(
        "mate-cb",
        40,
        116,
        "Podanie do stopera",
        "safe",
        "Nie tracisz piłki, ale stoper dostaje ją pod kątem i z presją nadchodzącą z boku.",
        "Ryzyko przenosi się na kolegę, przewaga nie powstaje.",
      ),
    ],
    missExplanation:
      "W pułapce pressingowej liczy się kierunek podania, a nie sam fakt zagrania.",
    missConsequence: "Rywal domyka trójkę zawodników i odbiera piłkę.",
  },

  /* ----------------------------------------------- OBROŃCA / OBRONA ---- */
  {
    id: "def-d-5",
    position: "defender",
    phase: "defense",
    theme: "Linia spalonego",
    title: "Rywal odwraca się przodem do gry",
    description:
      "Pomocnik rywala właśnie przyjął piłkę przodem, ale musi jeszcze spojrzeć w górę. Napastnik startuje za Twoje plecy, partner z linii jest równo z Tobą.",
    interaction: "move",
    markers: [
      m("self", "self", 44, 98, "Ty"),
      m("mate-cb", "mate", 62, 98, "Stoper"),
      m("mate-lb", "mate", 20, 100, "Boczny"),
      m("opp-ball", "opponent", 50, 66, "Z piłką"),
      m("ball", "ball", 52, 68),
      m("opp-st", "opponent", 46, 86, "Napastnik"),
    ],
    targets: [
      t(
        "step-up",
        46,
        86,
        "Krok do przodu razem z linią",
        "optimal",
        "Rywal nie ma jeszcze podniesionej głowy. Wspólny krok w górę unieważnia start napastnika, zanim podanie w ogóle powstanie.",
        "Napastnik ląduje na spalonym albo musi zatrzymać ruch.",
        13,
      ),
      t(
        "drop",
        44,
        114,
        "Cofnięcie za napastnika",
        "risky",
        "Zabezpiecza głębię, ale sam otwierasz przestrzeń między liniami i oddajesz 20 metrów boiska.",
        "Rywal wchodzi z piłką pod pole karne bez oporu.",
        13,
      ),
      t(
        "follow",
        58,
        90,
        "Indywidualne pójście za napastnikiem",
        "wrong",
        "Zrywasz linię — partner zostaje z dziurą obok siebie i cała pułapka przestaje działać.",
        "Powstaje wolny korytarz między stoperami.",
        12,
      ),
    ],
    missExplanation:
      "Decyzja linii obrony zapada w momencie przyjęcia rywala, nie po podaniu.",
    missConsequence: "Napastnik dostaje piłkę w biegu za linią.",
  },
  {
    id: "def-d-6",
    position: "defender",
    phase: "defense",
    theme: "Obrona przewagi 2v3",
    title: "Kontratak, jesteś w mniejszości",
    description:
      "Rywal biegnie trójką na dwóch. Ty jesteś najbliżej piłki, partner cofa się środkiem, wasz pomocnik dobiega 15 metrów z tyłu.",
    interaction: "move",
    markers: [
      m("self", "self", 48, 76, "Ty"),
      m("mate-cb", "mate", 58, 92, "Stoper"),
      m("mate-back", "mate", 44, 40, "Wracający pomocnik"),
      m("opp-ball", "opponent", 46, 58, "Z piłką"),
      m("ball", "ball", 48, 60),
      m("opp-left", "opponent", 22, 62),
      m("opp-right", "opponent", 74, 62),
    ],
    targets: [
      t(
        "delay",
        47,
        68,
        "Opóźnianie przed rywalem z piłką",
        "optimal",
        "W mniejszości gra się o czas, nie o piłkę. Cofając się przodem do rywala zmuszasz go do dryblingu i dajesz partnerowi 3 sekundy na powrót.",
        "Przewaga rywala znika, zanim dojdzie do strzału.",
        13,
      ),
      t(
        "tackle",
        46,
        58,
        "Wejście w odbiór",
        "wrong",
        "Jedno minięcie i zostaje 1 obrońca na 3 rywali — koszt błędu jest nieproporcjonalny do szansy odbioru.",
        "Rywal wchodzi w pole karne z podwójną przewagą.",
        11,
      ),
      t(
        "cover-right",
        70,
        70,
        "Krycie zawodnika po prawej",
        "risky",
        "Ma sens, gdy partner już panuje nad piłką — teraz zostawiasz podającego całkowicie bez presji.",
        "Rywal spokojnie wybiera najlepszą opcję i podaje na czysto.",
        12,
      ),
    ],
    missExplanation:
      "W przewadze rywala pierwszym zadaniem jest spowolnienie akcji.",
    missConsequence: "Kontratak kończy się sytuacją strzelecką.",
  },

  /* ------------------------------------------------- POMOCNIK / ATAK ---- */
  {
    id: "mid-a-5",
    position: "midfielder",
    phase: "attack",
    theme: "Ruch pozorny",
    title: "Zwolnienie przestrzeni dla partnera",
    description:
      "Twój boczny obrońca wchodzi wysoko wewnętrznym korytarzem. Ty stoisz w tym samym półprzestrzeniu, kryty przez pomocnika rywala.",
    interaction: "move",
    markers: [
      m("self", "self", 66, 72, "Ty"),
      m("ball", "ball", 30, 92),
      m("mate-lb", "mate", 88, 66, "Wchodzący boczny"),
      m("mate-cb", "mate", 28, 90, "Z piłką"),
      m("mate-st", "mate", 50, 40, "Napastnik"),
      m("opp-mark", "opponent", 62, 62, "Kryje Ciebie"),
      m("opp-cb", "opponent", 52, 46),
    ],
    targets: [
      t(
        "clear-out",
        44,
        58,
        "Ruch w kierunku środka, zwolnienie korytarza",
        "optimal",
        "Zabierasz swojego rywala z półprzestrzeni. Boczny wbiega w pole, którego już nikt nie kontroluje — przewagę tworzy Twój ruch, nie Twoje podanie.",
        "Wchodzicie w pole karne bez kontaktu z obroną.",
        13,
      ),
      t(
        "show-ball",
        56,
        84,
        "Pokazanie się do piłki",
        "risky",
        "Klasyczny odruch, ale wchodzisz w ten sam korytarz co boczny i blokujecie się nawzajem.",
        "Rywal broni dwóch zawodników jednym ciałem.",
        13,
      ),
      t(
        "run-deep",
        70,
        44,
        "Wbiegnięcie za obronę tą samą stroną",
        "safe",
        "Nie szkodzi, ale rywal biegnie z Tobą i przestrzeń dla bocznego nadal nie powstaje.",
        "Akcja kończy się dośrodkowaniem z gorszej pozycji.",
        12,
      ),
    ],
    missExplanation:
      "Nie każdy ruch ma prowadzić do piłki — czasem jego celem jest zabranie przeciwnika.",
    missConsequence: "Korytarz pozostaje zamknięty, akcja się zatrzymuje.",
  },
  {
    id: "mid-a-6",
    position: "midfielder",
    phase: "attack",
    theme: "Kontrola tempa",
    title: "Przyjęcie z presją zza pleców",
    description:
      "Dostajesz piłkę tyłem do bramki rywala, pomocnik dotyka Twoich pleców. Skrzydłowy jest wolny szeroko, napastnik startuje w głąb.",
    interaction: "pass",
    markers: [
      m("self", "self", 50, 74, "Ty"),
      m("ball", "ball", 52, 76),
      m("mate-wide", "mate", 90, 78, "Skrzydłowy"),
      m("mate-st", "mate", 54, 44, "Napastnik w biegu"),
      m("mate-6", "mate", 46, 98, "Szóstka"),
      m("opp-back", "opponent", 50, 82, "Za plecami"),
      m("opp-cb", "opponent", 58, 52),
    ],
    targets: [
      t(
        "mate-6",
        46,
        98,
        "Kontakt wstecz do szóstki",
        "optimal",
        "Nie masz pola na obrót, ale masz przewagę informacji: szóstka widzi całe boisko i zagra w jeden kontakt tam, gdzie Ty musiałbyś się odwracać.",
        "Piłka trafia w wolną strefę szybciej, niż rywal przesunie blok.",
      ),
      t(
        "mate-st",
        54,
        44,
        "Obrót i podanie za obronę",
        "risky",
        "Nagradzane, gdy się uda, ale obrót z rywalem na plecach to najczęstsze źródło strat w środku pola.",
        "Strata w centralnej strefie i kontratak wprost na Waszą bramkę.",
      ),
      t(
        "mate-wide",
        90,
        78,
        "Odegranie na skrzydło",
        "safe",
        "Poprawne i bezpieczne, choć oddajesz najlepszą chwilę do gry pomiędzy liniami.",
        "Atak trwa, ale rywal zdąży się ustawić.",
      ),
    ],
    missExplanation:
      "Przy presji zza pleców pierwszy kontakt decyduje o całej akcji.",
    missConsequence: "Rywal odbiera piłkę w środku pola.",
  },

  /* ---------------------------------------------- POMOCNIK / OBRONA ---- */
  {
    id: "mid-d-5",
    position: "midfielder",
    phase: "defense",
    theme: "Cień na podanie",
    title: "Pressing kierunkowy na stopera",
    description:
      "Stoper rywala prowadzi piłkę środkiem. Za Tobą stoi ich „szóstka”, silniejsza noga stopera to prawa, a wasza pułapka działa przy lewej linii.",
    interaction: "move",
    markers: [
      m("self", "self", 50, 72, "Ty"),
      m("opp-cb", "opponent", 52, 92, "Z piłką"),
      m("ball", "ball", 54, 94),
      m("opp-6", "opponent", 48, 78, "Szóstka"),
      m("mate-wing", "mate", 22, 74, "Skrzydłowy"),
      m("mate-st", "mate", 66, 66, "Napastnik"),
    ],
    targets: [
      t(
        "curved-left",
        66,
        84,
        "Dobiegnięcie łukiem, zamykanie środka",
        "optimal",
        "Biegniesz tak, by ciałem zasłonić szóstkę i wypchnąć stopera na słabszą stronę, gdzie czeka pułapka. Kierunek dobiegania jest ważniejszy niż jego prędkość.",
        "Rywal gra tam, gdzie chcecie, i tracicie mu piłkę przy linii.",
        13,
      ),
      t(
        "straight",
        52,
        86,
        "Bieg prosto na piłkę",
        "risky",
        "Wywierasz presję, ale zostawiasz obie strony otwarte i szóstka wychodzi z cienia.",
        "Jedno podanie omija Ciebie i całą pierwszą linię.",
        12,
      ),
      t(
        "mark-6",
        48,
        78,
        "Krycie szóstki bez wyjścia do piłki",
        "safe",
        "Zamyka środek, ale stoper wchodzi z piłką bez żadnego oporu i sam tworzy przewagę.",
        "Rywal przenosi grę prowadząc piłkę 20 metrów.",
        11,
      ),
    ],
    missExplanation:
      "Pressing bez kontroli linii podania za plecami nie jest pressingiem.",
    missConsequence: "Rywal wychodzi z rozegrania jednym podaniem.",
  },
  {
    id: "mid-d-6",
    position: "midfielder",
    phase: "defense",
    theme: "Rest defence",
    title: "Wasz atak trwa, piłka jest po drugiej stronie",
    description:
      "Zespół atakuje prawą stroną, piłka jest przy linii. Rywal zostawił szybkiego skrzydłowego samego po lewej, Twój boczny obrońca jest wysoko.",
    interaction: "zone",
    markers: [
      m("self", "self", 62, 74, "Ty"),
      m("ball", "ball", 90, 52),
      m("mate-wide", "mate", 88, 50, "Nasz atak"),
      m("mate-cb", "mate", 56, 104, "Stoper"),
      m("opp-wing", "opponent", 18, 70, "Wolny skrzydłowy"),
      m("opp-cb", "opponent", 70, 40),
    ],
    targets: [
      t(
        "balance",
        40,
        84,
        "Ustawienie po stronie przeciwnej do piłki",
        "optimal",
        "Rest defence to nie cofanie się — to zajęcie miejsca, przez które pójdzie ewentualny kontratak. Jesteś pierwszą przeszkodą, zanim strata w ogóle nastąpi.",
        "Ewentualny kontratak spotyka presję już w środku pola.",
        14,
      ),
      t(
        "support-ball",
        80,
        62,
        "Asekuracja przy piłce",
        "risky",
        "Pomaga w ataku, ale wasza lewa strona zostaje pusta na 40 metrów.",
        "Pierwsza strata kończy się biegiem skrzydłowego sam na sam.",
        13,
      ),
      t(
        "deep",
        56,
        112,
        "Cofnięcie do własnego pola karnego",
        "wrong",
        "Zbyt daleko — wypadasz z akcji ofensywnej i i tak nie zdążysz do kontratakującego przy linii.",
        "Tracicie zawodnika w ataku bez zysku w obronie.",
        13,
      ),
    ],
    missExplanation:
      "O obronie kontrataku decyduje ustawienie w trakcie własnego ataku.",
    missConsequence: "Strata piłki natychmiast zamienia się w sytuację bramkową.",
  },

  /* ------------------------------------------------ NAPASTNIK / ATAK ---- */
  {
    id: "fwd-a-5",
    position: "forward",
    phase: "attack",
    theme: "Ruch z martwego pola",
    title: "Start zza pleców stopera",
    description:
      "Pomocnik podnosi głowę z 35 metra. Stoper rywala obserwuje piłkę i widzi Cię kątem oka, drugi stoper jest wysunięty.",
    interaction: "move",
    markers: [
      m("self", "self", 52, 60, "Ty"),
      m("ball", "ball", 50, 90),
      m("mate-10", "mate", 48, 88, "Z piłką"),
      m("mate-wing", "mate", 86, 58, "Skrzydłowy"),
      m("opp-cb1", "opponent", 46, 52, "Kryje Ciebie"),
      m("opp-cb2", "opponent", 66, 50),
    ],
    targets: [
      t(
        "blindside",
        70,
        36,
        "Start za plecami, na zewnętrzną stronę stopera",
        "optimal",
        "Wychodzisz z pola widzenia obrońcy w chwili, gdy patrzy on na piłkę. To pół sekundy przewagi, którego nie da się nadrobić prędkością.",
        "Dostajesz piłkę w biegu, bez kontaktu z obroną.",
        13,
      ),
      t(
        "straight-run",
        50,
        36,
        "Prosty bieg do przodu",
        "risky",
        "Obrońca ma Cię cały czas w polu widzenia i biegnie równolegle — wygrywa pierwszy kontakt.",
        "Podanie kończy się przechwytem lub spalonym.",
        12,
      ),
      t(
        "drop",
        54,
        76,
        "Zejście do piłki",
        "safe",
        "Dostajesz piłkę pod nogę, ale zabierasz zespołowi jedyną groźbę za linią obrony.",
        "Rywal spokojnie podchodzi do linii pola karnego.",
        12,
      ),
    ],
    missExplanation:
      "Wartość startu zależy od tego, gdzie patrzy obrońca, nie od jego długości.",
    missConsequence: "Obrona kontroluje sytuację bez wysiłku.",
  },
  {
    id: "fwd-a-6",
    position: "forward",
    phase: "attack",
    theme: "Timing w polu karnym",
    title: "Skrzydłowy przygotowuje dośrodkowanie",
    description:
      "Skrzydłowy jest przy linii końcowej i za moment zagra niską piłkę. Jeden obrońca kryje bliższy słupek, drugi cofa się z Tobą.",
    interaction: "move",
    markers: [
      m("self", "self", 52, 30, "Ty"),
      m("ball", "ball", 88, 16),
      m("mate-wing", "mate", 86, 16, "Dośrodkowuje"),
      m("mate-second", "mate", 50, 46, "Druga linia"),
      m("opp-near", "opponent", 62, 18, "Bliższy słupek"),
      m("opp-mark", "opponent", 46, 26, "Kryje Ciebie"),
    ],
    targets: [
      t(
        "delay-far",
        34,
        20,
        "Zatrzymanie i start na dalszy słupek",
        "optimal",
        "Przerwanie ruchu na pół sekundy odkleja Cię od obrońcy, który biegnie dalej. Dalszy słupek to strefa, której nikt nie kryje przy niskim dośrodkowaniu.",
        "Wchodzisz w piłkę bez kontaktu, z otwartą bramką.",
        13,
      ),
      t(
        "near-post",
        64,
        18,
        "Atak na bliższy słupek",
        "risky",
        "Groźne przy dośrodkowaniu w powietrzu, teraz jednak wbiegasz w miejsce już obsadzone przez obrońcę.",
        "Piłka odbija się od obrońcy, tracicie okazję.",
        12,
      ),
      t(
        "penalty-spot",
        50,
        28,
        "Pozostanie przy jedenastce",
        "safe",
        "Rozsądne, ale zostajesz w polu widzenia obrońcy, który po prostu wybija piłkę przed Tobą.",
        "Dośrodkowanie zostaje przecięte.",
        12,
      ),
    ],
    missExplanation:
      "W polu karnym decyduje moment startu, a nie samo miejsce ustawienia.",
    missConsequence: "Dośrodkowanie przechodzi bez adresata.",
  },

  /* --------------------------------------------- NAPASTNIK / OBRONA ---- */
  {
    id: "fwd-d-5",
    position: "forward",
    phase: "defense",
    theme: "Pułapka pressingowa",
    title: "Wyznaczasz stronę pressingu",
    description:
      "Bramkarz rywala ma piłkę, obaj stoperzy są rozstawieni. Wasz skrzydłowy po prawej jest szybki i gotowy do domknięcia, lewa strona jest odsłonięta.",
    interaction: "press",
    markers: [
      m("self", "self", 50, 78, "Ty"),
      m("opp-gk", "opponent", 50, 122, "Bramkarz"),
      m("ball", "ball", 52, 124),
      m("opp-cb-l", "opponent", 26, 106, "Lewy stoper"),
      m("opp-cb-r", "opponent", 74, 106, "Prawy stoper"),
      m("mate-wing-r", "mate", 82, 84, "Nasz skrzydłowy"),
      m("mate-6", "mate", 50, 62, "Szóstka"),
    ],
    targets: [
      t(
        "opp-cb-r",
        74,
        106,
        "Pressing na prawego stopera",
        "optimal",
        "Zamykasz stronę, na której macie gotowe domknięcie skrzydłowym. Pressing to wybór kierunku, a nie bieg do najbliższej piłki.",
        "Rywal zostaje zamknięty przy linii i tracicie mu piłkę wysoko.",
      ),
      t(
        "opp-cb-l",
        26,
        106,
        "Pressing na lewego stopera",
        "wrong",
        "Wypychasz grę na stronę, której nie obstawiacie — rywal jednym podaniem wychodzi z pressingu.",
        "Cały zespół biegnie w pustkę i traci ustawienie.",
      ),
      t(
        "opp-gk",
        50,
        122,
        "Pressing bezpośrednio na bramkarza",
        "risky",
        "Może zadziałać przy słabym bramkarzu, ale zwykle otwiera obu stoperów i pierwszą linię omija długie podanie.",
        "Rywal wybija piłkę na wolne pole za wasz pressing.",
      ),
    ],
    missExplanation:
      "Bez wskazania kierunku pressing zespołowy przestaje być skoordynowany.",
    missConsequence: "Rywal wychodzi z własnej połowy bez straty.",
  },
  {
    id: "fwd-d-6",
    position: "forward",
    phase: "defense",
    theme: "Blokowanie rozgrywającego",
    title: "Rywal buduje przez szóstkę",
    description:
      "Zespół rywala rozgrywa spokojnie, ich „szóstka” dostaje każdą piłkę i nadaje tempo. Wasz blok jest ustawiony, ale zawsze spóźniony o jedno podanie.",
    interaction: "zone",
    markers: [
      m("self", "self", 50, 74, "Ty"),
      m("opp-cb-l", "opponent", 34, 104, "Stoper"),
      m("ball", "ball", 36, 106),
      m("opp-cb-r", "opponent", 68, 104, "Stoper"),
      m("opp-6", "opponent", 50, 88, "Szóstka"),
      m("mate-8", "mate", 40, 62, "Pomocnik"),
    ],
    targets: [
      t(
        "shadow",
        50,
        82,
        "Ustawienie w cieniu szóstki",
        "optimal",
        "Zamiast biegać za piłką, odcinasz jedynego zawodnika, który zmienia tempo gry rywala. Stoperzy mogą podawać do siebie — to dla was nic nie kosztuje.",
        "Rywal gra wyłącznie w poprzek i sam oddaje inicjatywę.",
        13,
      ),
      t(
        "press-cb",
        34,
        100,
        "Wyjście na stopera z piłką",
        "risky",
        "Widowiskowe, ale za Twoimi plecami szóstka dostaje piłkę i cały blok zostaje ominięty.",
        "Rywal wchodzi w środek pola z przewagą.",
        12,
      ),
      t(
        "deep",
        50,
        60,
        "Cofnięcie do linii pomocy",
        "wrong",
        "Oddajesz 25 metrów i przestajesz być punktem zaczepienia — zespół broni się o jedną linię za nisko.",
        "Rywal rozgrywa bez żadnego oporu aż pod pole karne.",
        12,
      ),
    ],
    missExplanation:
      "Praca napastnika w obronie polega na odcinaniu, nie na gonieniu piłki.",
    missConsequence: "Rywal kontroluje tempo całego meczu.",
  },
];

export function scenariosFor(
  position: string,
  phase: string,
): IQScenario[] {
  return IQ_SCENARIOS.filter(
    (s) => s.position === position && s.phase === phase,
  );
}
