/**
 * Regression test: slot-2 gym session exercise ID validity.
 *
 * Verifies that every exercise in a gym session generated by
 * `addMissingGymSessions` / `buildGymSessionDay` resolves to an approved
 * canonical record — fixing the [invalid-exercise-id] failures reported for
 * Rozgrzewka dynamiczna, Przysiad goblet, RDL / Hip hinge,
 * Stabilizacja core, and Rozciąganie.
 */

import { describe, it, expect } from "vitest";
import type { Profile, SessionDay, DayType, ExerciseItem } from "./types";
import { normalizeSessionCategory, isMainGymSession } from "./sessionClassification";
import { addMissingGymSessions } from "./weekFinalization";
import { getExerciseDefinition, isApprovedCanonicalExercise } from "./exerciseLibrary";
import { validatePlanExerciseContract } from "./planExerciseContract";
import { calculateWeeklyMinimumRequirements } from "./weeklyRequirements";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeProfile(over: Partial<Profile> = {}): Profile {
  return {
    name: "Test",
    age: 22,
    position: "midfielder",
    level: "intermediate",
    goal: "general",
    secondaryLimiter: null,
    clubTrainingDays: [],
    individualTrainingDays: [],
    usualMatchDay: "none",
    matchDate: null,
    equipment: ["barbell", "dumbbells", "kettlebell"],
    painInjury: false,
    doubleSessionsAllowed: "no",
    guardianConsent: true,
    onboardingComplete: true,
    createdAt: "",
    seasonPhase: "preseason",
    seasonStage: null,
    competitionLevel: "iv_liga",
    weeklyMatches: false,
    hasGym: true,
    hasPitch: true,
    hasSprintSpace: true,
    ...over,
  };
}

function baseDay(dayType: DayType, date: string, over: Partial<SessionDay> = {}): SessionDay {
  const raw: SessionDay = {
    date,
    dayOfWeek: 1,
    dayName: "Dzień",
    dayType,
    title: "",
    goalLabel: "",
    intensity: "umiarkowana",
    durationMin: 45,
    reason: "",
    safetyNote: null,
    whyToday: "",
    sessionType: "",
    goalOfSession: "",
    riskManaged: "",
    avoidToday: "",
    mdLabel: null,
    slotLabel: null,
    sections: { warmup: [], main: [], accessory: [], footballTransfer: [], cooldown: [] },
    secondSession: null,
    ...over,
  };
  return normalizeSessionCategory(raw);
}

function gymDay(date: string): SessionDay {
  return baseDay("training", date, {
    title: "Siła dolna — przysiad",
    sessionType: "Siła / moc",
    intensity: "wysoka",
  });
}

function restDay(date: string): SessionDay {
  return baseDay("rest", date, {
    title: "Dzień wolny",
    sessionType: "Dzień wolny",
    intensity: "niska",
    durationMin: 0,
  });
}

/** All ExerciseItems across warmup + main + accessory + cooldown. */
function collectExercises(session: SessionDay): ExerciseItem[] {
  const s = session.sections;
  return [...s.warmup, ...s.main, ...s.accessory, ...s.footballTransfer, ...s.cooldown];
}

/** Returns [session, slot] pairs generated (added) by addMissingGymSessions. */
function findGeneratedGymSessions(
  before: SessionDay[],
  after: SessionDay[],
): Array<{ session: SessionDay; slot: 1 | 2 }> {
  const results: Array<{ session: SessionDay; slot: 1 | 2 }> = [];

  after.forEach((dayAfter, i) => {
    const dayBefore = before[i];
    const beforeMainIsGym = dayBefore ? isMainGymSession(dayBefore) : false;
    const beforeSecondIsGym = dayBefore?.secondSession
      ? isMainGymSession(dayBefore.secondSession)
      : false;

    if (!beforeMainIsGym && isMainGymSession(dayAfter)) {
      results.push({ session: dayAfter, slot: 1 });
    }
    if (!beforeSecondIsGym && dayAfter.secondSession && isMainGymSession(dayAfter.secondSession)) {
      results.push({ session: dayAfter.secondSession, slot: 2 });
    }
  });

  return results;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("buildGymSessionDay — wygenerowane ID ćwiczeń są kanoniczne", () => {
  const DATES_2026_W35 = [
    "2026-08-24",
    "2026-08-25",
    "2026-08-26",
    "2026-08-27",
    "2026-08-28",
    "2026-08-29",
    "2026-08-30",
  ];

  function buildWeekWithOneGym(): SessionDay[] {
    // 1 gym session on Monday, rest days for the remainder — gives room for
    // addMissingGymSessions to insert a second gym session.
    return [
      gymDay(DATES_2026_W35[0]),
      restDay(DATES_2026_W35[1]),
      restDay(DATES_2026_W35[2]),
      restDay(DATES_2026_W35[3]),
      restDay(DATES_2026_W35[4]),
      restDay(DATES_2026_W35[5]),
      restDay(DATES_2026_W35[6]),
    ];
  }

  it("1. brak błędów invalid-exercise-id w wygenerowanej sesji gym", () => {
    const profile = makeProfile();
    const weekPlan = buildWeekWithOneGym();
    const requirements = calculateWeeklyMinimumRequirements({ profile, weekPlan });
    const { weekPlan: repaired } = addMissingGymSessions(weekPlan, requirements, profile);

    const issues = validatePlanExerciseContract(repaired);
    const gymIssues = issues.filter((i) => i.code === "invalid-exercise-id");

    expect(gymIssues).toHaveLength(0);
  });

  it("2. każde wygenerowane ID ćwiczenia wskazuje na zatwierdzoną kanonową definicję", () => {
    const profile = makeProfile();
    const weekPlan = buildWeekWithOneGym();
    const requirements = calculateWeeklyMinimumRequirements({ profile, weekPlan });
    const { weekPlan: repaired } = addMissingGymSessions(weekPlan, requirements, profile);

    const generated = findGeneratedGymSessions(buildWeekWithOneGym(), repaired);
    expect(generated.length).toBeGreaterThanOrEqual(1);

    for (const { session } of generated) {
      const exercises = collectExercises(session);
      for (const ex of exercises) {
        const def = ex.exerciseId ? getExerciseDefinition(ex.exerciseId) : undefined;
        expect(
          isApprovedCanonicalExercise(def),
          `"${ex.name}" (exerciseId: ${ex.exerciseId}) nie jest zatwierdzonym kanonowym ID`,
        ).toBe(true);
      }
    }
  });

  it("3. wielokrotna generacja jest deterministyczna", () => {
    const profile = makeProfile();
    const requirements = calculateWeeklyMinimumRequirements({
      profile,
      weekPlan: buildWeekWithOneGym(),
    });

    const run1 = addMissingGymSessions(buildWeekWithOneGym(), requirements, profile);
    const run2 = addMissingGymSessions(buildWeekWithOneGym(), requirements, profile);

    const gen1 = findGeneratedGymSessions(buildWeekWithOneGym(), run1.weekPlan);
    const gen2 = findGeneratedGymSessions(buildWeekWithOneGym(), run2.weekPlan);

    expect(gen1.length).toBe(gen2.length);

    for (let i = 0; i < gen1.length; i++) {
      const ids1 = collectExercises(gen1[i].session).map((e) => e.exerciseId);
      const ids2 = collectExercises(gen2[i].session).map((e) => e.exerciseId);
      expect(ids1).toEqual(ids2);
    }
  });
});
