import type { VisionTest } from "./types";

/**
 * Pełna biblioteka testów Vision Lab.
 * To jedyne źródło prawdy o testach — komponenty i serwis analizy czytają stąd.
 */
export const VISION_TESTS: VisionTest[] = [
  // ---------------- JUMP LAB ----------------
  {
    id: "cmj",
    name: "CMJ",
    category: "jump",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 60,
    goal: "Ocena mocy dolnej części ciała w wyskoku dosiężnym.",
    whatItMeasures:
      "Wysokość wyskoku, czas kontaktu, symetria odbicia i stabilność lądowania.",
    setupInstructions: [
      "Ustaw kamerę z boku na wysokości bioder, 3–4 m od zawodnika.",
      "Cała sylwetka i stopy muszą być w kadrze.",
      "Dobre, równomierne oświetlenie bez cieni na podłożu.",
    ],
    validRules: [
      "Widoczne obie stopy przez cały wyskok.",
      "Ręce na biodrach lub swobodny zamach — zgodnie z wariantem.",
      "Brak podbiegu, odbicie z miejsca.",
    ],
    measuredMetrics: ["Wysokość wyskoku", "Czas w powietrzu", "Symetria", "Stabilność lądowania"],
  },
  {
    id: "broad-jump",
    name: "Broad Jump",
    category: "jump",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 60,
    goal: "Ocena mocy poziomej i eksplozywności odbicia w dal.",
    whatItMeasures: "Długość skoku, kąt odbicia i kontrola lądowania.",
    setupInstructions: [
      "Kamera z boku, prostopadle do linii skoku.",
      "Widoczna linia startu i pełna strefa lądowania.",
      "Zaznacz linię startu taśmą.",
    ],
    validRules: [
      "Odbicie z obu nóg z miejsca.",
      "Widoczna linia startu i miejsce lądowania.",
      "Lądowanie utrzymane bez cofnięcia stopy.",
    ],
    measuredMetrics: ["Długość skoku", "Kąt odbicia", "Kontrola lądowania"],
  },
  {
    id: "pogo-jumps",
    name: "Pogo Jumps",
    category: "jump",
    difficulty: "intermediate",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 2,
    restSeconds: 90,
    goal: "Ocena sztywności ścięgnistej i reaktywności podłoża.",
    whatItMeasures: "Czas kontaktu, wysokość, indeks reaktywnej siły (RSI).",
    setupInstructions: [
      "Kamera z boku, wysoki FPS (120–240).",
      "Widoczne stopy i kontakt z podłożem.",
      "Sztywne kostki, minimalny zgięcie kolan.",
    ],
    validRules: [
      "Serie ciągłych odbić bez zatrzymania.",
      "Widoczny wyraźny kontakt z podłożem.",
      "Minimalne uginanie kolan.",
    ],
    measuredMetrics: ["Czas kontaktu", "Wysokość", "RSI"],
  },
  {
    id: "drop-jump",
    name: "Drop Jump",
    category: "jump",
    difficulty: "advanced",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 90,
    goal: "Ocena cyklu rozciągnięcie-skurcz i reaktywnej mocy.",
    whatItMeasures: "Czas kontaktu, wysokość wyskoku, RSI, kontrola lądowania.",
    setupInstructions: [
      "Skrzynia 30 cm, kamera z boku, wysoki FPS.",
      "Widoczne zejście ze skrzyni i kontakt z podłożem.",
      "Zejście krokiem, nie wyskokiem ze skrzyni.",
    ],
    validRules: [
      "Zejście ze skrzyni krokiem w dół.",
      "Natychmiastowe odbicie po kontakcie.",
      "Widoczny kontakt obu stóp.",
    ],
    measuredMetrics: ["Czas kontaktu", "Wysokość", "RSI", "Kontrola lądowania"],
  },
  {
    id: "single-leg-hop",
    name: "Single-Leg Hop",
    category: "jump",
    difficulty: "intermediate",
    cameraView: "side",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 60,
    goal: "Ocena mocy jednonóż i asymetrii między kończynami.",
    whatItMeasures: "Długość skoku każdej nogi, asymetria, stabilność lądowania.",
    setupInstructions: [
      "Kamera z boku, widoczna linia startu.",
      "Wykonaj skok osobno lewą i prawą nogą.",
      "Lądowanie na tej samej nodze.",
    ],
    validRules: [
      "Odbicie i lądowanie na tej samej nodze.",
      "Lądowanie utrzymane 2 sekundy.",
      "Widoczna linia startu.",
    ],
    measuredMetrics: ["Długość L", "Długość P", "Asymetria", "Stabilność lądowania"],
  },

  // ---------------- SPRINT LAB ----------------
  {
    id: "sprint-5m",
    name: "Sprint 5 m",
    category: "sprint",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena pierwszego kroku i przyspieszenia startowego.",
    whatItMeasures: "Czas na 5 m, pierwszy krok, kąt pochylenia tułowia.",
    setupInstructions: [
      "Kamera z boku, prostopadle do toru.",
      "Zaznacz linię startu i mety (5 m).",
      "Cała sylwetka i stopy widoczne.",
    ],
    validRules: [
      "Widoczna linia startu i mety.",
      "Start z miejsca bez falstartu.",
      "Wysoki FPS dla wiarygodnego czasu.",
    ],
    measuredMetrics: ["Czas 5 m", "Pierwszy krok", "Pochylenie tułowia"],
  },
  {
    id: "sprint-10m",
    name: "Sprint 10 m",
    category: "sprint",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena przyspieszenia na dystansie 10 m.",
    whatItMeasures: "Czas na 10 m, mechanika przyspieszenia, pochylenie tułowia.",
    setupInstructions: [
      "Kamera z boku, prostopadle do toru.",
      "Zaznacz linię startu i mety (10 m).",
      "Cała sylwetka i stopy widoczne przez cały bieg.",
    ],
    validRules: [
      "Widoczna linia startu i mety.",
      "Start z miejsca bez falstartu.",
      "Kamera stabilna, wysoki FPS.",
    ],
    measuredMetrics: ["Czas 10 m", "Mechanika przyspieszenia", "Pochylenie tułowia"],
  },
  {
    id: "sprint-20m",
    name: "Sprint 20 m",
    category: "sprint",
    difficulty: "intermediate",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 180,
    goal: "Ocena przyspieszenia i przejścia do prędkości maksymalnej.",
    whatItMeasures: "Czas na 20 m, faza przyspieszenia i osiągana prędkość.",
    setupInstructions: [
      "Kamera z boku, obejmująca cały tor lub panning.",
      "Zaznacz linię startu i mety (20 m).",
      "Cała sylwetka widoczna.",
    ],
    validRules: [
      "Widoczna linia startu i mety.",
      "Start z miejsca.",
      "Stabilne nagranie całego dystansu.",
    ],
    measuredMetrics: ["Czas 20 m", "Faza przyspieszenia", "Prędkość maksymalna"],
  },
  {
    id: "flying-10m",
    name: "Flying 10 m",
    category: "sprint",
    difficulty: "advanced",
    cameraView: "side",
    minimumFps: 240,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 180,
    goal: "Ocena prędkości maksymalnej na lotnym odcinku 10 m.",
    whatItMeasures: "Prędkość maksymalna, częstotliwość i długość kroku.",
    setupInstructions: [
      "Rozbieg przed strefą pomiaru.",
      "Kamera z boku, prostopadle do lotnego odcinka.",
      "Wysoki FPS (240) wymagany.",
    ],
    validRules: [
      "Pełna prędkość wejścia w strefę pomiaru.",
      "Widoczne obie linie strefy.",
      "FPS 240 dla wiarygodności.",
    ],
    measuredMetrics: ["Prędkość maks.", "Częstotliwość kroku", "Długość kroku"],
  },

  // ---------------- COD & BRAKING LAB ----------------
  {
    id: "5-10-5",
    name: "5-10-5",
    category: "cod",
    difficulty: "intermediate",
    cameraView: "front",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena zmiany kierunku o 180° i zdolności hamowania.",
    whatItMeasures: "Czas całkowity, czas hamowania, symetria zwrotów.",
    setupInstructions: [
      "Trzy linie w odstępie 5 m.",
      "Kamera z przodu obejmująca wszystkie linie.",
      "Widoczne stopy przy każdym zwrocie.",
    ],
    validRules: [
      "Dotknięcie każdej linii ręką.",
      "Widoczne wszystkie trzy linie.",
      "Bez poślizgu poza kadr.",
    ],
    measuredMetrics: ["Czas całkowity", "Czas hamowania", "Symetria zwrotów"],
  },
  {
    id: "braking-test",
    name: "Braking Test",
    category: "cod",
    difficulty: "intermediate",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena zdolności do gwałtownego wyhamowania z pełnej prędkości.",
    whatItMeasures: "Dystans hamowania, liczba kroków, kontrola tułowia.",
    setupInstructions: [
      "Rozbieg + strefa hamowania.",
      "Kamera z boku, widoczne stopy.",
      "Zaznacz linię, przy której należy zatrzymać.",
    ],
    validRules: [
      "Pełna prędkość przed hamowaniem.",
      "Widoczny moment zatrzymania.",
      "Stopy w kadrze przez całe hamowanie.",
    ],
    measuredMetrics: ["Dystans hamowania", "Liczba kroków", "Kontrola tułowia"],
  },
  {
    id: "l-drill",
    name: "L-Drill",
    category: "cod",
    difficulty: "advanced",
    cameraView: "45deg",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena zwinności, zmian kierunku i pracy nóg w kształcie litery L.",
    whatItMeasures: "Czas całkowity, płynność zwrotów, praca nóg.",
    setupInstructions: [
      "Trzy pachołki w układzie L (5 m).",
      "Kamera pod kątem 45° obejmująca cały układ.",
      "Widoczna cała trasa.",
    ],
    validRules: [
      "Prawidłowe obiegnięcie pachołków.",
      "Widoczny cały układ.",
      "Bez ścinania trasy.",
    ],
    measuredMetrics: ["Czas całkowity", "Płynność zwrotów", "Praca nóg"],
  },
  {
    id: "t-test",
    name: "T-Test",
    category: "cod",
    difficulty: "intermediate",
    cameraView: "front",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 2,
    restSeconds: 150,
    goal: "Ocena zwinności wielokierunkowej i kroków dostawnych.",
    whatItMeasures: "Czas całkowity, kroki dostawne, symetria stron.",
    setupInstructions: [
      "Układ pachołków w kształcie T.",
      "Kamera z przodu obejmująca całe T.",
      "Widoczne stopy.",
    ],
    validRules: [
      "Twarz zawsze do przodu przy krokach dostawnych.",
      "Dotknięcie każdego pachołka.",
      "Widoczny cały układ.",
    ],
    measuredMetrics: ["Czas całkowity", "Kroki dostawne", "Symetria stron"],
  },
  {
    id: "sprint-to-stop",
    name: "Sprint to Stop",
    category: "cod",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena kontroli deceleracji po sprincie.",
    whatItMeasures: "Czas sprintu, dystans zatrzymania, kontrola lądowania kroku.",
    setupInstructions: [
      "Sprint 10 m + strefa zatrzymania.",
      "Kamera z boku, widoczne stopy.",
      "Zaznacz strefę zatrzymania.",
    ],
    validRules: [
      "Pełen sprint przed strefą.",
      "Zatrzymanie w wyznaczonej strefie.",
      "Stopy widoczne przy zatrzymaniu.",
    ],
    measuredMetrics: ["Czas sprintu", "Dystans zatrzymania", "Kontrola kroku"],
  },

  // ---------------- TECHNIQUE ROOM ----------------
  {
    id: "landing-mechanics",
    name: "Landing Mechanics",
    category: "technique",
    difficulty: "beginner",
    cameraView: "front",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 60,
    goal: "Ocena jakości i bezpieczeństwa lądowania.",
    whatItMeasures: "Ustawienie kolan, symetria, amortyzacja lądowania.",
    setupInstructions: [
      "Kamera z przodu na wysokości kolan.",
      "Widoczne obie nogi i stopy.",
      "Lądowanie ze skrzyni lub wyskoku.",
    ],
    validRules: [
      "Widoczne obie nogi z przodu.",
      "Pełne lądowanie w kadrze.",
      "Dobre oświetlenie kolan.",
    ],
    measuredMetrics: ["Ustawienie kolan", "Symetria", "Amortyzacja"],
  },
  {
    id: "squat-pattern",
    name: "Squat Pattern",
    category: "technique",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 30,
    recommendedFps: 60,
    attempts: 2,
    restSeconds: 45,
    goal: "Ocena wzorca przysiadu i mobilności.",
    whatItMeasures: "Głębokość, ustawienie tułowia, ruch bioder i kolan.",
    setupInstructions: [
      "Kamera z boku na wysokości bioder.",
      "Widoczna cała sylwetka od stóp po głowę.",
      "Stopy i plecy w kadrze.",
    ],
    validRules: [
      "Cała sylwetka widoczna z boku.",
      "Powolne, kontrolowane powtórzenia.",
      "Stopy nie wychodzą z kadru.",
    ],
    measuredMetrics: ["Głębokość", "Ustawienie tułowia", "Ruch bioder"],
  },
  {
    id: "lunge-pattern",
    name: "Lunge Pattern",
    category: "technique",
    difficulty: "beginner",
    cameraView: "side",
    minimumFps: 30,
    recommendedFps: 60,
    attempts: 2,
    restSeconds: 45,
    goal: "Ocena wzorca wykroku i stabilności jednonóż.",
    whatItMeasures: "Ustawienie kolana, głębokość, stabilność tułowia.",
    setupInstructions: [
      "Kamera z boku, widoczna cała sylwetka.",
      "Widoczne oba kolana.",
      "Kontrolowane tempo.",
    ],
    validRules: [
      "Cała sylwetka w kadrze.",
      "Wyraźnie widoczne przednie kolano.",
      "Bez utraty równowagi poza kadr.",
    ],
    measuredMetrics: ["Ustawienie kolana", "Głębokość", "Stabilność tułowia"],
  },
  {
    id: "sprint-side-view",
    name: "Sprint Side View",
    category: "technique",
    difficulty: "intermediate",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 2,
    restSeconds: 120,
    goal: "Ocena mechaniki biegu z profilu.",
    whatItMeasures: "Wznos kolana, wyprost bioder, ustawienie tułowia, kontakt stopy.",
    setupInstructions: [
      "Kamera z boku, panning za zawodnikiem.",
      "Wysoki FPS dla klatek kluczowych.",
      "Widoczna cała sylwetka.",
    ],
    validRules: [
      "Profil zawodnika widoczny w biegu.",
      "Wysoki FPS.",
      "Stabilne prowadzenie kamery.",
    ],
    measuredMetrics: ["Wznos kolana", "Wyprost bioder", "Ustawienie tułowia"],
  },
  {
    id: "cod-technique",
    name: "Change of Direction Technique",
    category: "technique",
    difficulty: "advanced",
    cameraView: "45deg",
    minimumFps: 60,
    recommendedFps: 120,
    attempts: 3,
    restSeconds: 90,
    goal: "Ocena techniki zmiany kierunku i ustawienia ciała.",
    whatItMeasures: "Kąt ustawienia stopy, ustawienie kolana, pochylenie tułowia.",
    setupInstructions: [
      "Kamera pod kątem 45° do kierunku zwrotu.",
      "Widoczne stopy i kolana.",
      "Dobre oświetlenie podłoża.",
    ],
    validRules: [
      "Widoczny moment zwrotu.",
      "Stopy i kolana w kadrze.",
      "Bez ścinania trasy.",
    ],
    measuredMetrics: ["Kąt stopy", "Ustawienie kolana", "Pochylenie tułowia"],
  },
  {
    id: "braking-mechanics",
    name: "Braking Mechanics",
    category: "technique",
    difficulty: "advanced",
    cameraView: "side",
    minimumFps: 120,
    recommendedFps: 240,
    attempts: 3,
    restSeconds: 120,
    goal: "Ocena mechaniki hamowania i absorpcji sił.",
    whatItMeasures: "Ustawienie tułowia, zgięcie kolan, liczba kroków hamowania.",
    setupInstructions: [
      "Kamera z boku, widoczne stopy.",
      "Wysoki FPS dla klatek kontaktu.",
      "Strefa hamowania zaznaczona.",
    ],
    validRules: [
      "Widoczna pełna faza hamowania.",
      "Stopy w kadrze.",
      "Wysoki FPS.",
    ],
    measuredMetrics: ["Ustawienie tułowia", "Zgięcie kolan", "Kroki hamowania"],
  },
];

export function getVisionTest(id: string): VisionTest | undefined {
  return VISION_TESTS.find((t) => t.id === id);
}

export function getTestsByCategory(category: string): VisionTest[] {
  return VISION_TESTS.filter((t) => t.category === category);
}
