/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DataRightsRouteImport } from './routes/data-rights'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SesjaDateRouteImport } from './routes/sesja.$date'
import { Route as TabsStartRouteImport } from './routes/_tabs.start'
import { Route as TabsScoutingRouteImport } from './routes/_tabs.scouting'
import { Route as TabsProfilRouteImport } from './routes/_tabs.profil'
import { Route as TabsPlanRouteImport } from './routes/_tabs.plan'
import { Route as TabsAparatRouteImport } from './routes/_tabs.aparat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRightsRoute = DataRightsRouteImport.update({
  id: '/data-rights',
  path: '/data-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SesjaDateRoute = SesjaDateRouteImport.update({
  id: '/sesja/$date',
  path: '/sesja/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsStartRoute = TabsStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => TabsRoute,
} as any)
const TabsScoutingRoute = TabsScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfilRoute = TabsProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPlanRoute = TabsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAparatRoute = TabsAparatRouteImport.update({
  id: '/aparat',
  path: '/aparat',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-rights': typeof DataRightsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/aparat': typeof TabsAparatRoute
  '/plan': typeof TabsPlanRoute
  '/profil': typeof TabsProfilRoute
  '/scouting': typeof TabsScoutingRoute
  '/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-rights': typeof DataRightsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/aparat': typeof TabsAparatRoute
  '/plan': typeof TabsPlanRoute
  '/profil': typeof TabsProfilRoute
  '/scouting': typeof TabsScoutingRoute
  '/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-rights': typeof DataRightsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/_tabs/aparat': typeof TabsAparatRoute
  '/_tabs/plan': typeof TabsPlanRoute
  '/_tabs/profil': typeof TabsProfilRoute
  '/_tabs/scouting': typeof TabsScoutingRoute
  '/_tabs/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-rights'
    | '/onboarding'
    | '/privacy-policy'
    | '/terms'
    | '/aparat'
    | '/plan'
    | '/profil'
    | '/scouting'
    | '/start'
    | '/sesja/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-rights'
    | '/onboarding'
    | '/privacy-policy'
    | '/terms'
    | '/aparat'
    | '/plan'
    | '/profil'
    | '/scouting'
    | '/start'
    | '/sesja/$date'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/auth'
    | '/data-rights'
    | '/onboarding'
    | '/privacy-policy'
    | '/terms'
    | '/_tabs/aparat'
    | '/_tabs/plan'
    | '/_tabs/profil'
    | '/_tabs/scouting'
    | '/_tabs/start'
    | '/sesja/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataRightsRoute: typeof DataRightsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  SesjaDateRoute: typeof SesjaDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-rights': {
      id: '/data-rights'
      path: '/data-rights'
      fullPath: '/data-rights'
      preLoaderRoute: typeof DataRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesja/$date': {
      id: '/sesja/$date'
      path: '/sesja/$date'
      fullPath: '/sesja/$date'
      preLoaderRoute: typeof SesjaDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/start': {
      id: '/_tabs/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof TabsStartRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/scouting': {
      id: '/_tabs/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof TabsScoutingRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profil': {
      id: '/_tabs/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof TabsProfilRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/plan': {
      id: '/_tabs/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof TabsPlanRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/aparat': {
      id: '/_tabs/aparat'
      path: '/aparat'
      fullPath: '/aparat'
      preLoaderRoute: typeof TabsAparatRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAparatRoute: typeof TabsAparatRoute
  TabsPlanRoute: typeof TabsPlanRoute
  TabsProfilRoute: typeof TabsProfilRoute
  TabsScoutingRoute: typeof TabsScoutingRoute
  TabsStartRoute: typeof TabsStartRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAparatRoute: TabsAparatRoute,
  TabsPlanRoute: TabsPlanRoute,
  TabsProfilRoute: TabsProfilRoute,
  TabsScoutingRoute: TabsScoutingRoute,
  TabsStartRoute: TabsStartRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AuthRoute: AuthRoute,
  DataRightsRoute: DataRightsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  SesjaDateRoute: SesjaDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
