/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SesjaDateRouteImport } from './routes/sesja.$date'
import { Route as TabsStartRouteImport } from './routes/_tabs.start'
import { Route as TabsPlanRouteImport } from './routes/_tabs.plan'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SesjaDateRoute = SesjaDateRouteImport.update({
  id: '/sesja/$date',
  path: '/sesja/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsStartRoute = TabsStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => TabsRoute,
} as any)
const TabsPlanRoute = TabsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof TabsPlanRoute
  '/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof TabsPlanRoute
  '/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_tabs/plan': typeof TabsPlanRoute
  '/_tabs/start': typeof TabsStartRoute
  '/sesja/$date': typeof SesjaDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding' | '/plan' | '/start' | '/sesja/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/plan' | '/start' | '/sesja/$date'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/onboarding'
    | '/_tabs/plan'
    | '/_tabs/start'
    | '/sesja/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SesjaDateRoute: typeof SesjaDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesja/$date': {
      id: '/sesja/$date'
      path: '/sesja/$date'
      fullPath: '/sesja/$date'
      preLoaderRoute: typeof SesjaDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/start': {
      id: '/_tabs/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof TabsStartRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/plan': {
      id: '/_tabs/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof TabsPlanRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsPlanRoute: typeof TabsPlanRoute
  TabsStartRoute: typeof TabsStartRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsPlanRoute: TabsPlanRoute,
  TabsStartRoute: TabsStartRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SesjaDateRoute: SesjaDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
